# Generated by Django 4.1.5 on 2023-02-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0002_mentor_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor_reg',
            name='student',
        ),
    ]
