# Generated by Django 4.1.5 on 2023-02-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0003_remove_mentor_reg_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.mentor_reg')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
    ]
