# Generated by Django 4.1.5 on 2023-03-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0004_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('blood_group', models.CharField(max_length=200, null=True)),
                ('religion', models.CharField(max_length=200, null=True)),
                ('caste', models.CharField(max_length=200, null=True)),
                ('permanent_address', models.CharField(max_length=200, null=True)),
                ('contact_address', models.CharField(max_length=200, null=True)),
                ('mob_number', models.CharField(max_length=200, null=True)),
                ('telephone_number', models.CharField(max_length=200, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
    ]
