# Generated by Django 4.1.5 on 2023-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0005_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
