# Generated by Django 4.1.5 on 2023-03-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0006_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Councelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=200, null=True)),
                ('time', models.TimeField(max_length=200, null=True)),
                ('feedback', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.mentor_reg')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
    ]
