# Generated by Django 4.1.5 on 2023-03-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0007_councelling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='councelling',
            old_name='feedback',
            new_name='arts',
        ),
        migrations.AddField(
            model_name='councelling',
            name='behaviour',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='co_curricular',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='comm_skill',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='enter_skill',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='inter_skill',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='leader_quality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='sports_games',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='sugge_improve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='team_working',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='tech_skill',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='councelling',
            name='well_groomed_not',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
