# Generated by Django 4.1.5 on 2023-03-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0008_rename_feedback_councelling_arts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='councelling',
            name='Extra_curricular',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
