# Generated by Django 4.1.5 on 2023-03-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0009_councelling_extra_curricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentee_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('father_profession', models.CharField(max_length=200, null=True)),
                ('father_age', models.CharField(max_length=200, null=True)),
                ('work_place', models.CharField(max_length=200, null=True)),
                ('father_number', models.CharField(max_length=200, null=True)),
                ('mother_name', models.CharField(max_length=200, null=True)),
                ('mother_profession', models.CharField(max_length=200, null=True)),
                ('mother_number', models.CharField(max_length=200, null=True)),
                ('siblings_in_SJCET', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('local_guardian', models.CharField(max_length=200, null=True)),
                ('local_age', models.CharField(max_length=200, null=True)),
                ('guardian_proffe', models.CharField(max_length=200, null=True)),
                ('guardian_address', models.CharField(max_length=200, null=True)),
                ('guardian_number', models.CharField(max_length=200, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
    ]
