# Generated by Django 4.1.5 on 2023-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0011_mentee_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentee_first_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_impression', models.CharField(max_length=200, null=True)),
                ('sourceof_income', models.CharField(max_length=200, null=True)),
                ('background', models.CharField(max_length=200, null=True)),
                ('parental_harmony', models.CharField(max_length=200, null=True)),
                ('relationship', models.CharField(max_length=200, null=True)),
                ('atmosphere', models.CharField(max_length=200, null=True)),
                ('morality', models.CharField(max_length=200, null=True)),
                ('social_outlook', models.CharField(max_length=200, null=True)),
                ('rd_habit', models.CharField(max_length=200, null=True)),
                ('behaviour', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('weakness', models.CharField(max_length=200, null=True)),
                ('adjustment', models.CharField(max_length=200, null=True)),
                ('addiction', models.CharField(max_length=200, null=True)),
                ('improvement', models.CharField(max_length=200, null=True)),
                ('concern', models.CharField(max_length=200, null=True)),
                ('language_lab', models.CharField(max_length=200, null=True)),
                ('fitness_for_mca', models.CharField(max_length=200, null=True)),
                ('life_goals', models.CharField(max_length=200, null=True)),
                ('competency', models.CharField(max_length=200, null=True)),
                ('representations', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
