# Generated by Django 4.1.5 on 2023-03-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0012_mentee_first_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee_first_meeting',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.mentor_reg'),
        ),
        migrations.AddField(
            model_name='mentee_first_meeting',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg'),
        ),
    ]
