# Generated by Django 4.1.5 on 2023-03-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0013_mentee_first_meeting_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quali', models.CharField(max_length=200, null=True)),
                ('college', models.CharField(max_length=200, null=True)),
                ('university', models.CharField(max_length=200, null=True)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('medium', models.CharField(max_length=200, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
        migrations.CreateModel(
            name='overall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introvert_or_extrovert', models.CharField(max_length=200, null=True)),
                ('abnormal_behaviour', models.CharField(max_length=200, null=True)),
                ('health_condition', models.CharField(max_length=200, null=True)),
                ('stability', models.CharField(max_length=200, null=True)),
                ('hyperactive', models.CharField(max_length=200, null=True)),
                ('personal_hygiene', models.CharField(max_length=200, null=True)),
                ('addiction', models.CharField(max_length=200, null=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.mentor_reg')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_description', models.CharField(max_length=200, null=True)),
                ('submission_date', models.CharField(max_length=200, null=True)),
                ('feedback', models.CharField(max_length=200, null=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.mentor_reg')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_duration', models.CharField(max_length=200, null=True)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('stay_arranged', models.CharField(max_length=200, null=True)),
                ('no_hostel_owner', models.CharField(max_length=200, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DSM_App.student_reg')),
            ],
        ),
    ]
