# Generated by Django 4.1.5 on 2023-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0014_qualification_overall_assignment_accomodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='stay_duration',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='stay_duration_from',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='stay_duration_to',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
