# Generated by Django 4.1.5 on 2023-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSM_App', '0015_remove_accomodation_stay_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
